using System;
using System.IO;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Platform;
using Ionic.Zip;
using Slithin.Core;

namespace Slithin.Tools
{
    public class BackupTool : ITool
    {
        public IImage Image
        {
            get
            {
                var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();

                return new Bitmap(assets.Open(new Uri($"avares://Slithin/Resources/backup.png")));
            }
        }

        public ScriptInfo Info => new("Backup", "Internal", "Backup all your files");

        public bool IsConfigurable => false;

        public Control GetModal()
        {
            return null;
        }

        public void Invoke(object data)
        {
            ServiceLocator.PostAction(async () =>
            {
                NotificationService.Show("Start Compressing");

                using (var zip = new ZipFile())
                {
                    NotificationService.Show("Compressing");
                    zip.AddDirectory(Path.Combine(ServiceLocator.ConfigBaseDir, "Notebooks"), "Notebooks");
                    zip.AddDirectory(Path.Combine(ServiceLocator.ConfigBaseDir, "Templates"), "Templates");
                    zip.AddDirectory(Path.Combine(ServiceLocator.ConfigBaseDir, "Scripts"), "Scripts");
                    zip.AddDirectory(Path.Combine(ServiceLocator.ConfigBaseDir, "Screens"), "Screens");

                    zip.Comment = "This backup was generated by Slithin";

                    if (!Directory.Exists(ServiceLocator.BackupDir))
                    {
                        Directory.CreateDirectory(ServiceLocator.BackupDir);
                    }

                    zip.Save(Path.Combine(ServiceLocator.BackupDir, $"Backup_from_{DateTime.Now:yyyy-dd-M--HH-mm-ss}" + ".zip"));
                }

                NotificationService.Show("Finished");
                await Task.Delay(1000);

                NotificationService.Hide();
            });
        }
    }
}
